[package]
name = "s-kademlia"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
async-std = "0.99"
bytes = "0.4"
smallvec = "0.6"
arrayvec = "0.5.1"
multihash = "0.8.0"
criterion = "0.3.0"

[dev-dependencies]
quickcheck = "0.9.0"
model = "0.1"

[[bench]]
name = "lock"
harness = false

[profile.release]
debug = true