[package]
name = "s-kademlia"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"
description = "s/kademlia in rust"
categories = ["dht", "kademlia"]
readme = "README.md"

[dependencies]
async-trait = "0.1"
async-std = "0.99"
bytes = "0.4.12"
zeroize = "1.0.0"
time = "0.1.42"
smallvec = "0.6"
arrayvec = "0.5.1"
disco = {git = "https://github.com/rust-p2p/disco", default-features = false}
multihash = "0.8.0"
criterion = "0.3.0"
crossbeam-utils = "0.6.6"

[dependencies.ed25519-dalek]
git = "https://github.com/dvc94ch/ed25519-dalek"
branch = "update-rand"

# [dev-dependencies]
# quickcheck = "0.9.0"
# model = "0.1"
